### ISSUE TITLE
How to install plugin

### ISSUE THREAD

**Issue by Kimttar** [csm10495/openrct2-csm10495-plugin#6]
I have no programing knowledge and have just been grabbing the .js file and adding it into my Plugin folder. None of the .js files seem to work. Any suggestions?

**Comment by csm10495** [comment]
I haven't really gotten around to making releases fully work yet. So it needs to be built manually in the meantime.
[csm10495-plugin.js.txt](https://github.com/csm10495/openrct2-csm10495-plugin/files/8962321/csm10495-plugin.js.txt)

Try using this file instead. Remove .txt from the name so its just csm10495-plugin.js

**Comment by Kimttar** [comment]
Thanks! That worked! Awesome plugin.

**Comment by csm10495** [comment]
Yay. I'll leave this open till i get releases working. Thanks again.

**Comment by csm10495** [comment]
Woot. Got releases working. New versions (if they ever come) will be here: https://github.com/csm10495/openrct2-csm10495-plugin/releases/tag/latest

Thanks again. Closing out.
